### ISSUE TITLE
Crafting guide page number is difficult to read

### ISSUE THREAD

**Issue by ExcaliburZero** [minetest-LOTT/Lord-of-the-Test#20]
Currently in the crafting guide ("lottinventory:crafts_book") the page number that the player is on is displayed to the right of the ">>" box in white text. However, because the background of the crafting guide is a light color it makes the page number somewhat difficult to read.

Screenshot
![screenshot_1730729169](https://cloud.githubusercontent.com/assets/4276196/6095039/439cf772-af16-11e4-99b5-13ed39becf1a.png)

**Comment by Amaz1** [comment]
The only way to fix this is to change the background, because I don't think the text can be coloured... (I would be very happy to be proved wrong on this!)

So, @ExcaliburZero  and @fishyWET  what do you think to this background for the craft books?
![image](https://cloud.githubusercontent.com/assets/4390945/6099053/94e2deaa-afe6-11e4-8b96-82708aaec4df.png)

Let me know what you think, and if you like it, I can push it.

**Comment by ExcaliburZero** [comment]
@Amaz1 
Yeah, that looks better.

I'm not very familiar with forumspecs, but I did some looking around and testing. However I was unable to find any way to change the label's text color. I don't know why there isn't such a function, as it would make sense to have something like it.

You're welcome.

**Comment by Amaz1** [comment]
I think that Minetest doesn't support coloured text at all at the moment... There is a pull to add it, number 2136... It is for chat, but I presume that it would work for formspecs as well...

**Comment by Amaz1** [comment]
cd4a2175858b135c5e09079c903f7d9dcaa3017c
(Slightly modified version of the above image, at fishyWET's request.)

**Comment by Amaz1** [comment]
Great... Messed up the commit message!
Apparently it was pushed because:
"Due to the fact that on the old background, the page number could be seen." XD
I suppose that is what comes of committing late at night!

Also, Happy birthday to the LOTT repository! (And also to my start of contributions to it!)
:birthday:
