### ISSUE TITLE
Orc food & medicine don't go away

### ISSUE THREAD

**Issue by BadToad2000** [minetest-LOTT/Lord-of-the-Test#51]
Several issues with these orc items.
1) When using Orc food or medicine, the item count does not decrease.

2) When a player is an orc they should be able to use these items without the vision problems (getting the gray/white screens).

3) Should races other than orcs benefit from using these? Currently these items satiate/heal everyone equally, with just a negative impact on vision. Maybe other races should only get +1 hunger/health along with the vision problem.

4) Most foods give an increase to satiation (increase hunger bar), but orc food sets the hud hunger bar to 20. Do you all wish to keep this behavior for orcs?

I'll fix these if you let me know what the desired functionality is.

**Comment by BadToad2000** [comment]
Followup question. Are beverages (beer, wine, ale...) supposed to restore hp or hunger? Currently, they call minetest.item_eat (hp) instead of hud.item_eat (hunger)

Would anyone mind if I change these to restore hunger, and return the empty glass to the user's inventory?

**Comment by fishyWET** [comment]
I cannot answer the prior question as it is not coded by me. Hey, @Amaz1 
But for the latter, it is very much intended that those alcoholic beverages restore hp instead of hunger. Been reworking on lottpotion recently and will be pushing in the rework within these few days, so I wouldn't suggest pushing those in, unless your want your changes overwritten.

**Comment by BadToad2000** [comment]
My confusion stems from the beverages in "dwarves" mod being treated as food. Either approach is fine.

It would be nice if when one drank a beverage or potion the empty container was returned to their inventory.

BTW the replacement code in hud.item_eat is incorrect:
`			itemstack:add_item(replace_with_item) -- note: replace_with_item is optional`

should read:
`			user:get_inventory():add_item("main", replace_with_item) -- note: replace_with_item is optional`


There are no calls passing "replace_with_item" yet, so issue not seen.

**Comment by fishyWET** [comment]
The hud mod is taken from the old version of https://github.com/BlockMen/hud_hunger
From what I can see, this particular line is still present in there; https://github.com/BlockMen/hud_hunger/blob/master/hunger/functions.lua#L262

Just to confirm, i tested out the code myself, it runs without errors. Unless you cannot run it without an error, there's no need to replace it.

**Comment by BadToad2000** [comment]
The replace item code doesn't generate an error, it only replaces the last item in the itemstack (incoming itemstack had 1 item).

Changing to BlockMen's newer code would be good.
https://github.com/BlockMen/hud_hunger/blob/master/hunger/functions.lua#L260&L273

**Comment by Amaz1** [comment]
Hi! I'm sorry I've taken so long to reply... I've been pretty busy recently! 
> 1) When using Orc food or medicine, the item count does not decrease.

Yep, this is a bug. I've been meaning to fix it for a while, but if you want to fix it, go ahead, please do!!

> 2) When a player is an orc they should be able to use these items without the vision problems (getting the gray/white screens).

Sounds like a good idea to me.

> 3) Should races other than orcs benefit from using these? Currently these items satiate/heal everyone equally, with just a negative impact on vision. Maybe other races should only get +1 hunger/health along with the vision problem.

I'm not sure about this... If orcs can use them without downsides, then the vision impact might be enough for other races... The orc food/medicine was based on the books, when Merry and Pipin are taken captives by the orcs, and are given food/medicine to allow them to continue on their strenuous march. So it seems to be that it should work for all races.

> 4) Most foods give an increase to satiation (increase hunger bar), but orc food sets the hud hunger bar to 20. Do you all wish to keep this behavior for orcs?

I'm not entirely sure by what you mean here... I think it works fine as it is now?!

Yeah, updating everything to the latest HUD code would be good... If you want to do it, feel free, otherwise I can do it at some point...! I think that would fix the bug that you mentioned with replace_with_item?

Again, I'm very sorry about the time I took to reply to this!

**Comment by BadToad2000** [comment]
Amaz1, no worries about your taking time to answer. I plan to wait until after fishyWET's changes anyway.

For item 4, I mean that typically when you eat something it restores a specific amount of hunger (or satiation). Let's say an item restores 4 hunger, so if you were at 10 your hunger would go to 14. But orc food would set the value to 20 regardless of you starting hunger level. Technically your hunger can go to 30 (150%), with 20 being displayed, and the game lets you eat even when you are at or above 20. However, doing that with orc food setting hunger to 20 could make you hungrier that when you started. I think it would be better to have orc food behave like other foods, and restore a given amount, maybe 12 or so, since the foods that go into it restore 9 (with raw meats) or 17 (once meats are cooked).

Is there some level of fullness, where maybe the player should not be able to eat more? So you wouldn't be able to eat if your hunger was 25 or greater to start with ("I couldn't eat another bite"). Players could still reach the 30 max when eating foods with high satiation ("I can't believe I ate the whole thing"). If you had this behavior, then one could address item 3 by saying non-orcs have to be fairly hungry (maybe 10 hunger or less) before they would willingly eat orc food.

**Comment by fishyWET** [comment]
LOTT is discontinued.
LOTT 2.0 repository will be launched soon.

**Comment by agwilt** [comment]
Wait what!? Where? Is there going to be any cool new stuff?

**Comment by Amaz1** [comment]
I think that fishyWET may be exaggerating just a little... There are still some little things I want to push, and then I'll continue to push bugfixes, but for the most part it will be discontinued.

But LOTT is not going to die! The main reason that we're doing this is that LOTT contains a lot of really really bad code from when fishy was first coding it :stuck_out_tongue: We came to the decision that it would be probably easier to recode it from scratch than to replace the bad code... We're also not going to be basing it on Minetest Game, because keeping up to date with the changes in that was a nightmare... afaik, however, not a line of code has been written for it yet :smile: There will be **very** awesome new features though!

If any of you want to discuss it, feel free to join irc and ask about it/make suggestions in #lordofthetest.

**Comment by agwilt** [comment]
I'm current studying hard for my A-levels, but once I have more free time I'll certainly join in :grinning:

**Comment by Amaz1** [comment]
I fixed the bug part of this issue: https://github.com/minetest-LOTT/Lord-of-the-Test/commit/b23f4187f981ef6bde67ca1f7335babf29d45c78
